version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    image: kittygram_backend
    build: ./backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/static
      - media:/app/media
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn kittygram_backend.wsgi:application --bind 0.0.0.0:8000"

  frontend:
    container_name: frontend
    image: kittygram_frontend
    build: ./frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    container_name: gateway
    image: kittygram_gateway
    build: ./nginx
    depends_on:
      - backend
      - frontend
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
