server {
<<<<<<< HEAD
    listen 80;

    client_max_body_size 20m;

    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /admin/ {
        proxy_pass http://backend:8000/admin/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /static/ {
        alias /static/;
    }

    location /media/ {
        alias /media/;
    }
=======
  listen 80;
  index index.html;

  location /api/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:8000/api/;
  }
  location /admin/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:8000/admin/;
  }

  location /media/ {
    alias /media/;
  }

  location /static/ {
    alias /static/;
  }

  location / {
    alias /static/;
    try_files $uri $uri/ /index.html;
  }
>>>>>>> f559300 (Configure Kittygram Docker and CI/CD)
}
